const escapeHtml = (value: string | number) =>
  String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")

export function downloadPdf(
  title: string,
  headers: string[],
  rows: (string | number)[][],
  subtitle?: string
) {
  const head = headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("")
  const body = rows
    .map(
      (r) =>
        `<tr>${r.map((c) => `<td>${escapeHtml(c)}</td>`).join("")}</tr>`
    )
    .join("")

  const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: "Segoe UI", Arial, sans-serif; color: #0f172a; margin: 32px; }
  .doc-head { border-bottom: 2px solid #4f46e5; padding-bottom: 16px; margin-bottom: 20px; }
  .doc-head h1 { font-size: 20px; margin: 0; }
  .doc-head p { margin: 4px 0 0; color: #64748b; font-size: 12px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { background: #eef2ff; color: #312e81; text-align: left; padding: 8px 10px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }
  td { border-bottom: 1px solid #e2e8f0; padding: 8px 10px; }
  tbody tr:nth-child(even) { background: #f8fafc; }
  .foot { margin-top: 24px; color: #94a3b8; font-size: 10px; }
</style>
</head>
<body>
  <div class="doc-head">
    <h1>${escapeHtml(title)}</h1>
    ${subtitle ? `<p>${escapeHtml(subtitle)}</p>` : ""}
    <p>Generated by NexusHR · ${escapeHtml(new Date().toLocaleString())}</p>
  </div>
  <table>
    <thead><tr>${head}</tr></thead>
    <tbody>${body || `<tr><td colspan="${headers.length}">No records</td></tr>`}</tbody>
  </table>
  <p class="foot">NexusHR — Human Resource Management System</p>
  <script>
    window.addEventListener("load", function () {
      setTimeout(function () { window.print() }, 300)
      setTimeout(function () { window.close() }, 2000)
    })
  </script>
</body>
</html>`

  const win = window.open("", "_blank", "width=920,height=720")
  if (!win) return
  win.document.write(html)
  win.document.close()
}
